/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account with `user` role. Returns access token in body for compatibility and sets access/refresh httpOnly cookies.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Authenticates with email/password. Returns access token in body for compatibility and sets access/refresh httpOnly cookies.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Uses the refresh token from the `refreshToken` httpOnly cookie.
         *     Performs **token rotation**: the old refresh token is revoked and a new one is issued.
         *     Also sets a fresh `accessToken` httpOnly cookie.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Revokes the refresh token when present and clears access/refresh cookies. Does not require a valid access token.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/rooms/{objectKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get room photo
         * @description Proxies a room photo stored in MinIO. Browser clients use this backend URL instead of direct MinIO access.
         */
        get: operations["getRoomPhoto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active buildings
         * @description Returns localized building labels using `X-Locale` or `Accept-Language`.
         */
        get: operations["listBuildings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking-purposes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active booking purposes
         * @description Returns localized booking purpose labels using `X-Locale` or `Accept-Language`.
         */
        get: operations["listBookingPurposes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search rooms with availability
         * @description Returns a paginated list of active rooms with computed availability for the given date.
         *     Supports filtering by name, time range, equipment, and capacity.
         */
        get: operations["searchRooms"];
        put?: never;
        /** Create a room (admin) */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Room detail with time-slot timeline
         * @description Returns full room info and a timeline of time slots for the given date.
         *     Slot statuses: `available`, `occupied` (confirmed by another user),
         *     `pending` (pending by another user), `yours` (current user's booking of any status).
         */
        get: operations["getRoomDetail"];
        /**
         * Update a room (admin)
         * @description Full replacement of room data.
         */
        put: operations["updateRoom"];
        post?: never;
        /**
         * Soft-delete a room (admin)
         * @description Sets `is_active = false`. Existing bookings are NOT cancelled.
         */
        delete: operations["deleteRoom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all equipment types
         * @description Returns the full equipment catalogue. Used by the frontend for filter rendering.
         */
        get: operations["listEquipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a booking request
         * @description Creates a new booking with `pending` status.
         *
         *     **Overlap rules:**
         *     - Overlap with `confirmed` bookings → **409 BOOKING_CONFLICT** (blocked).
         *     - Overlap with `pending` bookings → **allowed** (multiple pending requests for the same slot are OK).
         *
         *     Checked inside a transaction with `SELECT ... FOR UPDATE`.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My active bookings
         * @description Returns the current user's bookings that are still upcoming
         *     (`pending` or `confirmed`, and `booking_date + end_time` is in the future).
         *     Sorted ascending by date/time.
         */
        get: operations["getMyBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/my/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My past / inactive bookings
         * @description Returns the current user's bookings that are expired, rejected, or cancelled.
         *     Sorted descending by date (newest first).
         */
        get: operations["getMyBookingHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cancel a booking
         * @description Only the booking owner (or an admin) can cancel.
         *     Only `pending` or `confirmed` bookings can be cancelled.
         *     Cannot cancel a booking that has already started.
         */
        patch: operations["cancelBooking"];
        trace?: never;
    };
    "/admin/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search all rooms (admin)
         * @description Returns a paginated list of rooms, including inactive ones.
         */
        get: operations["adminSearchRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/booking-purposes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all booking purposes */
        get: operations["listAdminBookingPurposes"];
        put?: never;
        /** Create booking purpose */
        post: operations["createBookingPurpose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/booking-purposes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update booking purpose labels/status */
        put: operations["updateBookingPurpose"];
        post?: never;
        /** Deactivate booking purpose */
        delete: operations["deactivateBookingPurpose"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/booking-purposes/{code}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reactivate booking purpose */
        patch: operations["reactivateBookingPurpose"];
        trace?: never;
    };
    "/admin/booking-purposes/{code}/hard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently delete a booking purpose and its linked bookings */
        delete: operations["hardDeleteBookingPurpose"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently delete a room */
        delete: operations["hardDeleteRoom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rooms/{roomId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reactivate an inactive room */
        patch: operations["reactivateRoom"];
        trace?: never;
    };
    "/admin/bookings/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending booking requests
         * @description Admin dashboard — paginated list of all pending bookings with user and room details.
         */
        get: operations["getPendingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List admin booking history
         * @description Admin dashboard — paginated list of all processed bookings (confirmed, rejected, cancelled).
         */
        get: operations["getAdminBookingHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/{bookingId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve a pending booking
         * @description Approves a pending booking inside a `SERIALIZABLE` transaction.
         *
         *     **Cascade auto-rejection:** all other `pending` bookings that overlap with the
         *     newly approved time slot are automatically rejected with a system-generated reason.
         *
         *     The response includes the list of auto-rejected bookings.
         */
        patch: operations["approveBooking"];
        trace?: never;
    };
    "/admin/bookings/{bookingId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a pending booking */
        patch: operations["rejectBooking"];
        trace?: never;
    };
    "/admin/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create new equipment
         * @description Adds a new equipment item to the catalogue.
         */
        post: operations["createEquipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/equipment/{equipmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update equipment
         * @description Updates an existing equipment item.
         */
        put: operations["updateEquipment"];
        post?: never;
        /**
         * Delete equipment
         * @description Soft-deletes or completely removes an equipment item.
         */
        delete: operations["deleteEquipment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard statistics
         * @description Returns aggregate metrics for the admin dashboard (pending count, occupancy rate, etc.)
         */
        get: operations["getAdminStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns server status and database connectivity.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        UserRole: "user" | "admin";
        /** @enum {string} */
        BookingStatus: "pending" | "confirmed" | "rejected" | "cancelled";
        /** @enum {string} */
        RoomType: "lab" | "auditorium" | "seminar" | "conference" | "studio" | "lecture_hall";
        /** @description Stable booking purpose code from the booking_purposes catalog. */
        BookingPurpose: string;
        /**
         * @description Priority: yours > yours_pending > occupied > pending > available
         * @enum {string}
         */
        TimeSlotStatus: "available" | "occupied" | "pending" | "yours" | "yours_pending";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
            department?: string | null;
            role: components["schemas"]["UserRole"];
            /** Format: date-time */
            createdAt: string;
        };
        EquipmentItem: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Tabler icon name (e.g. IconVideo) */
            icon: string;
        };
        BuildingOption: {
            code: string;
            label: string;
        };
        BookingPurposeOption: {
            code: string;
            label: string;
        };
        AdminBookingPurpose: {
            code: string;
            labelRu: string;
            labelEn: string;
            isActive: boolean;
            sortOrder: number;
        };
        RoomCard: {
            /** Format: uuid */
            id: string;
            /** @example LAB_402B */
            name: string;
            description?: string | null;
            roomType: components["schemas"]["RoomType"];
            capacity: number;
            building: string;
            buildingLabel?: string;
            floor: number;
            photos?: string[];
            equipment: components["schemas"]["EquipmentItem"][];
            availability: components["schemas"]["RoomAvailability"];
        };
        RoomAvailability: {
            isAvailable: boolean;
            /**
             * @description e.g. AVAILABLE NOW, BOOKED UNTIL 16:00, FULLY BOOKED, AVAILABLE
             * @example AVAILABLE NOW
             */
            label: string;
            /**
             * @description First free interval, e.g. 09:00 — 18:00
             * @example 09:00 — 18:00
             */
            availableTimeRange?: string | null;
        };
        RoomDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            roomType: components["schemas"]["RoomType"];
            capacity: number;
            building: string;
            buildingLabel?: string;
            floor: number;
            photos?: string[];
            /**
             * @description Room opens at this time
             * @example 08:00
             */
            openTime: string;
            /**
             * @description Room closes at this time
             * @example 20:00
             */
            closeTime: string;
            equipment: components["schemas"]["EquipmentItem"][];
            timeSlots: components["schemas"]["TimeSlot"][];
            userBookingsToday: components["schemas"]["UserBookingSummary"][];
        };
        TimeSlot: {
            /** @example 10:00 */
            startTime: string;
            /** @example 12:00 */
            endTime: string;
            status: components["schemas"]["TimeSlotStatus"];
            /** @description null when status is available */
            booking?: components["schemas"]["TimeSlotBooking"] | null;
        };
        TimeSlotBooking: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: uuid */
            userId: string;
        };
        UserBookingSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @example 14:00 */
            startTime: string;
            /** @example 16:30 */
            endTime: string;
            status: components["schemas"]["BookingStatus"];
        };
        Booking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            roomId: string;
            roomName: string;
            title: string;
            purpose: components["schemas"]["BookingPurpose"];
            /** Format: date */
            bookingDate: string;
            /** @example 14:00 */
            startTime: string;
            /** @example 16:30 */
            endTime: string;
            attendeeCount?: number | null;
            status: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        MyBooking: {
            /** Format: uuid */
            id: string;
            /**
             * @description Human-readable ID, e.g. #BK-88291-Q
             * @example #BK-88291-Q
             */
            bookingId: string;
            /** Format: uuid */
            roomId: string;
            /** @example RM_402 QUANTUM LAB */
            roomName: string;
            title: string;
            /** Format: date */
            bookingDate: string;
            /** @example 14:00 */
            startTime: string;
            /** @example 16:30 */
            endTime: string;
            /** @example SCIENCE BLOCK B */
            building: string;
            /** @example Авиамоторная */
            buildingLabel?: string;
            status: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        AdminPendingBooking: {
            /** Format: uuid */
            id: string;
            user: {
                /** Format: uuid */
                id: string;
                firstName: string;
                lastName: string;
                /** @example JD */
                initials: string;
                department?: string | null;
            };
            room: {
                /** Format: uuid */
                id: string;
                name: string;
                building: string;
            };
            title: string;
            purpose: components["schemas"]["BookingPurpose"];
            /** Format: date */
            bookingDate: string;
            /** @example 14:00 */
            startTime: string;
            /** @example 16:30 */
            endTime: string;
            attendeeCount?: number | null;
            status: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        AdminStats: {
            /** @example 24 */
            pendingCount: number;
            /**
             * @description Percentage of total room-hours occupied today (0-100)
             * @example 88
             */
            occupancyRate: number;
            /** @example 15 */
            todayBookingsCount: number;
            /** @example 42 */
            totalRooms: number;
            /** @example 40 */
            totalActiveRooms: number;
            bookingsByStatus?: {
                status: string;
                count: number;
            }[];
            popularRooms?: {
                /** Format: uuid */
                id: string;
                name: string;
                building: string;
                count: number;
            }[];
            bookingsByDayOfWeek?: {
                day: string;
                count: number;
            }[];
            occupancyByBuilding?: {
                building: string;
                occupancyRate: number;
            }[];
        };
        RoomFull: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            roomType: components["schemas"]["RoomType"];
            capacity: number;
            building: string;
            floor: number;
            /**
             * @description Room opens at this time
             * @example 08:00
             */
            openTime: string;
            /**
             * @description Room closes at this time
             * @example 20:00
             */
            closeTime: string;
            photos?: string[];
            equipment: components["schemas"]["EquipmentItem"][];
            /** Format: date-time */
            createdAt: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @description Must contain ≥1 uppercase, ≥1 lowercase, ≥1 digit */
            password: string;
            firstName: string;
            lastName: string;
            department?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CreateBookingRequest: {
            /** Format: uuid */
            roomId: string;
            title: string;
            purpose: components["schemas"]["BookingPurpose"];
            /**
             * Format: date
             * @description YYYY-MM-DD, must not be in the past
             */
            bookingDate: string;
            /** @example 14:00 */
            startTime: string;
            /**
             * @description Must be after startTime
             * @example 16:30
             */
            endTime: string;
            /** @description Must not exceed room capacity */
            attendeeCount?: number;
        };
        CreateRoomRequest: {
            name: string;
            description?: string | null;
            roomType: components["schemas"]["RoomType"];
            capacity: number;
            building: string;
            floor: number;
            /** @example 08:00 */
            openTime: string;
            /** @example 20:00 */
            closeTime: string;
            photos?: string[];
            equipmentIds?: string[];
        };
        UpdateRoomRequest: {
            name?: string;
            description?: string | null;
            roomType?: components["schemas"]["RoomType"];
            capacity?: number;
            building?: string;
            floor?: number;
            /** @example 08:00 */
            openTime?: string;
            /** @example 20:00 */
            closeTime?: string;
            photos?: string[];
            equipmentIds?: string[];
        };
        CreateRoomMultipartRequest: {
            name: string;
            description?: string | null;
            roomType: components["schemas"]["RoomType"];
            capacity: number;
            building: string;
            floor: number;
            /** @example 08:00 */
            openTime: string;
            /** @example 20:00 */
            closeTime: string;
            /**
             * Format: binary
             * @description Single PNG/JPG/WEBP image, max 5MB.
             */
            photo?: string;
            equipmentIds?: string[];
        };
        UpdateRoomMultipartRequest: components["schemas"]["CreateRoomMultipartRequest"] & {
            /** @description When true and no `photo` is sent, clears the current room photo. */
            removePhoto?: boolean;
        };
        RejectBookingRequest: {
            reason?: string;
        };
        CursorPaginationMeta: {
            hasMore: boolean;
            /** @description Base64-encoded cursor for the next page */
            nextCursor?: string | null;
        };
        CursorPaginationMetaWithTotal: {
            /** @description Total count matching current filters */
            total: number;
            hasMore: boolean;
            nextCursor?: string | null;
        };
        ErrorResponse: {
            error: {
                /**
                 * @description Machine-readable error code
                 * @example BOOKING_CONFLICT
                 */
                code: string;
                /** @description Human-readable error description */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        ValidationErrorResponse: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR";
                message: string;
                details: {
                    fields: {
                        field: string;
                        message: string;
                        code: string;
                    }[];
                };
            };
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example 1.0.0 */
            version: string;
            /** @description Server uptime in seconds */
            uptime: number;
            /** @example connected */
            database: string;
        };
    };
    responses: {
        /** @description Missing or invalid access token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Missing or invalid access token"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient permissions (admin required) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "Admin role required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request body validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                /** @description Seconds until the rate limit resets */
                "Retry-After"?: number;
                "X-RateLimit-Limit"?: number;
                "X-RateLimit-Remaining"?: number;
                "X-RateLimit-Reset"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMIT_EXCEEDED",
                 *         "message": "Too many requests, please try again later",
                 *         "details": {
                 *           "retryAfter": 45
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Number of items per page */
        LimitParam: number;
        /** @description Cursor from a previous response's `meta.nextCursor` */
        CursorParam: string;
        /** @description Free-text search */
        SearchParam: string;
        /** @description Date (YYYY-MM-DD). Defaults to today. */
        DateParam: string;
        /** @description Room UUID */
        RoomIdParam: string;
        /** @description Booking UUID */
        BookingIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "john.doe@university.edu",
                 *       "password": "SecureP@ss123",
                 *       "firstName": "John",
                 *       "lastName": "Doe",
                 *       "department": "Faculty of Computer Science"
                 *     }
                 */
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    /** @description accessToken=<jwt>; HttpOnly; Secure; SameSite=Strict; Path=/api; Max-Age=900 and refreshToken=<token>; HttpOnly; Secure; SameSite=Strict; Path=/api/auth; Max-Age=2592000 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["User"];
                            accessToken: string;
                        };
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "EMAIL_ALREADY_EXISTS",
                     *         "message": "This email is already registered"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "john.doe@university.edu",
                 *       "password": "SecureP@ss123"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    /** @description accessToken=<jwt>; HttpOnly; Secure; SameSite=Strict; Path=/api; Max-Age=900 and refreshToken=<token>; HttpOnly; Secure; SameSite=Strict; Path=/api/auth; Max-Age=2592000 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["User"];
                            accessToken: string;
                        };
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UNAUTHORIZED",
                     *         "message": "Invalid email or password"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New tokens issued */
            200: {
                headers: {
                    /** @description New accessToken and refreshToken cookies */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            accessToken: string;
                        };
                    };
                };
            };
            /** @description Refresh token missing, expired, or revoked */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "REFRESH_TOKEN_INVALID",
                     *         "message": "Refresh token is invalid, expired, or revoked"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            204: {
                headers: {
                    /** @description accessToken=; Max-Age=0 and refreshToken=; Max-Age=0 (clear cookies) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRoomPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room photo object path, e.g. `{roomId}/{fileName}`. */
                objectKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room photo bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                    "image/webp": string;
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listBuildings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Building catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["BuildingOption"][];
                    };
                };
            };
        };
    };
    listBookingPurposes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking purpose catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["BookingPurposeOption"][];
                    };
                };
            };
        };
    };
    searchRooms: {
        parameters: {
            query?: {
                /** @description Date (YYYY-MM-DD). Defaults to today. */
                date?: components["parameters"]["DateParam"];
                /** @description Free-text search */
                search?: components["parameters"]["SearchParam"];
                /** @description Building code. Defaults to aviamotornaya. */
                building?: string;
                /** @description Start of desired time range (HH:mm, 5-minute granularity) */
                timeFrom?: string;
                /** @description End of desired time range */
                timeTo?: string;
                /**
                 * @description Comma-separated equipment UUIDs. Rooms must have ALL listed equipment.
                 * @example uuid1,uuid2
                 */
                equipment?: string;
                /** @description Minimum room capacity */
                minCapacity?: number;
                /** @description Number of items per page */
                limit?: components["parameters"]["LimitParam"];
                /** @description Cursor from a previous response's `meta.nextCursor` */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated room list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoomCard"][];
                        meta: components["schemas"]["CursorPaginationMeta"];
                    };
                };
            };
            /** @description Invalid time range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
                "multipart/form-data": components["schemas"]["CreateRoomMultipartRequest"];
            };
        };
        responses: {
            /** @description Room created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoomFull"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRoomDetail: {
        parameters: {
            query?: {
                /** @description Date (YYYY-MM-DD). Defaults to today. */
                date?: components["parameters"]["DateParam"];
            };
            header?: never;
            path: {
                /** @description Room UUID */
                roomId: components["parameters"]["RoomIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room detail with timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoomDetail"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Room not found or inactive */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "ROOM_NOT_FOUND",
                     *         "message": "Room not found"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room UUID */
                roomId: components["parameters"]["RoomIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomRequest"];
                "multipart/form-data": components["schemas"]["UpdateRoomMultipartRequest"];
            };
        };
        responses: {
            /** @description Room updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoomFull"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room UUID */
                roomId: components["parameters"]["RoomIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room deactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listEquipment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Equipment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "eq-uuid-1",
                     *           "name": "Projector",
                     *           "icon": "IconVideo"
                     *         },
                     *         {
                     *           "id": "eq-uuid-2",
                     *           "name": "Whiteboard",
                     *           "icon": "IconPresentation"
                     *         },
                     *         {
                     *           "id": "eq-uuid-3",
                     *           "name": "Computers",
                     *           "icon": "IconDeviceDesktop"
                     *         },
                     *         {
                     *           "id": "eq-uuid-4",
                     *           "name": "Microphone",
                     *           "icon": "IconMicrophone"
                     *         },
                     *         {
                     *           "id": "eq-uuid-5",
                     *           "name": "Live Stream",
                     *           "icon": "IconBroadcast"
                     *         },
                     *         {
                     *           "id": "eq-uuid-6",
                     *           "name": "Spatial Audio",
                     *           "icon": "IconVolume"
                     *         },
                     *         {
                     *           "id": "eq-uuid-7",
                     *           "name": "Wi-Fi",
                     *           "icon": "IconWifi"
                     *         },
                     *         {
                     *           "id": "eq-uuid-8",
                     *           "name": "Linux Nodes",
                     *           "icon": "IconTerminal2"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        data: components["schemas"]["EquipmentItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "roomId": "room-uuid-1",
                 *       "title": "Advanced AI Seminar",
                 *       "purpose": "academic_lecture",
                 *       "bookingDate": "2026-04-10",
                 *       "startTime": "14:00",
                 *       "endTime": "16:30",
                 *       "attendeeCount": 35
                 *     }
                 */
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Booking created with status `pending` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Booking"];
                    };
                };
            };
            /** @description Validation error, invalid time range, or capacity exceeded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "ROOM_NOT_FOUND",
                     *         "message": "Room not found"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Time slot conflicts with a confirmed booking */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BOOKING_CONFLICT",
                     *         "message": "Requested time slot overlaps with a confirmed booking",
                     *         "details": {
                     *           "conflicting_booking_id": "uuid",
                     *           "conflicting_time_range": "14:00-16:00"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Booking date/time is in the past */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BOOKING_IN_PAST",
                     *         "message": "Cannot create a booking in the past"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getMyBookings: {
        parameters: {
            query?: {
                /** @description Free-text search */
                search?: components["parameters"]["SearchParam"];
                /** @description Number of items per page */
                limit?: components["parameters"]["LimitParam"];
                /** @description Cursor from a previous response's `meta.nextCursor` */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated active bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MyBooking"][];
                        meta: components["schemas"]["CursorPaginationMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyBookingHistory: {
        parameters: {
            query?: {
                /** @description Free-text search */
                search?: components["parameters"]["SearchParam"];
                /** @description Number of items per page */
                limit?: components["parameters"]["LimitParam"];
                /** @description Cursor from a previous response's `meta.nextCursor` */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated history bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MyBooking"][];
                        meta: components["schemas"]["CursorPaginationMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking UUID */
                bookingId: components["parameters"]["BookingIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: uuid */
                            id: string;
                            /** @enum {string} */
                            status: "cancelled";
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not the booking owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "NOT_OWNER",
                     *         "message": "You can only cancel your own bookings"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Booking already processed (not pending/confirmed) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BOOKING_ALREADY_PROCESSED",
                     *         "message": "Booking has already been processed"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Booking has already started */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BOOKING_IN_PAST",
                     *         "message": "Cannot cancel a booking that has already started"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminSearchRooms: {
        parameters: {
            query?: {
                /** @description Free-text search */
                search?: components["parameters"]["SearchParam"];
                /** @description Filter by status */
                status?: "active" | "inactive" | "all";
                /** @description Number of items per page */
                limit?: components["parameters"]["LimitParam"];
                /** @description Cursor from a previous response's `meta.nextCursor` */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated room list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoomCard"][];
                        meta: components["schemas"]["CursorPaginationMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminBookingPurposes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking purposes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminBookingPurpose"][];
                    };
                };
            };
        };
    };
    createBookingPurpose: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminBookingPurpose"];
            };
        };
        responses: {
            /** @description Created booking purpose */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBookingPurpose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated booking purpose */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deactivateBookingPurpose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reactivateBookingPurpose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reactivated booking purpose */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hardDeleteBookingPurpose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking purpose and linked bookings permanently deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hardDeleteRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room UUID */
                roomId: components["parameters"]["RoomIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room permanently deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reactivateRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room UUID */
                roomId: components["parameters"]["RoomIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room reactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoomFull"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getPendingBookings: {
        parameters: {
            query?: {
                /** @description Free-text search */
                search?: components["parameters"]["SearchParam"];
                /** @description Number of items per page */
                limit?: components["parameters"]["LimitParam"];
                /** @description Cursor from a previous response's `meta.nextCursor` */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated pending bookings with total count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminPendingBooking"][];
                        meta: components["schemas"]["CursorPaginationMetaWithTotal"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminBookingHistory: {
        parameters: {
            query?: {
                /** @description Free-text search */
                search?: components["parameters"]["SearchParam"];
                /** @description Number of items per page */
                limit?: components["parameters"]["LimitParam"];
                /** @description Cursor from a previous response's `meta.nextCursor` */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated booking history with total count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminPendingBooking"][];
                        meta: components["schemas"]["CursorPaginationMetaWithTotal"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    approveBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking UUID */
                bookingId: components["parameters"]["BookingIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking approved (with optional auto-rejected list) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            booking: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                status: "confirmed";
                                /** Format: date-time */
                                updatedAt: string;
                            };
                            /** @description Pending bookings that were auto-rejected due to overlap */
                            autoRejected: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                userId: string;
                                title: string;
                                startTime: string;
                                endTime: string;
                                reason: string;
                            }[];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Booking already processed or new time conflict detected */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Booking date/time is in the past */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BOOKING_IN_PAST",
                     *         "message": "Cannot approve a booking in the past"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rejectBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking UUID */
                bookingId: components["parameters"]["BookingIdParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "reason": "Room is reserved for maintenance on this date"
                 *     }
                 */
                "application/json": components["schemas"]["RejectBookingRequest"];
            };
        };
        responses: {
            /** @description Booking rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: uuid */
                            id: string;
                            /** @enum {string} */
                            status: "rejected";
                            statusReason?: string | null;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Booking is not pending */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BOOKING_ALREADY_PROCESSED",
                     *         "message": "Booking is no longer pending"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createEquipment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Projector */
                    name: string;
                    /** @example icon-projector */
                    icon: string;
                };
            };
        };
        responses: {
            /** @description Created equipment item */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EquipmentItem"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateEquipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example High-res Projector */
                    name: string;
                    /** @example icon-projector */
                    icon: string;
                };
            };
        };
        responses: {
            /** @description Updated equipment item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EquipmentItem"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteEquipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Equipment deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAdminStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminStats"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
